package com.kacperstasiak.repaymentassistant.UI;

import com.kacperstasiak.repaymentassistant.MVC.Controller;
import com.kacperstasiak.repaymentassistant.Debt;

/**
 * The user interface frame for adding or editing a debt instance
 *
 * @author Kacper Stasiak
 */
public class AddEditFrame extends javax.swing.JFrame {

    DebtsListFrame parent;
    Controller controller;
    Debt editing;

    /**
     * Creates a add new debt form
     *
     * @param parent The debts list frame that created this form
     * @param controller The controller that handles the main view
     */
    public AddEditFrame(DebtsListFrame parent, Controller controller) {
        this.parent = parent;
        this.controller = controller;
        initComponents();
        refInput.setValue(""); //NOI18N
        balInput.setValue(0.0);
        rateInput.setValue(0.0);
        payInput.setValue(0.0);
        errorLabel.setVisible(false);
        this.setTitle(java.util.ResourceBundle.getBundle("com/kacperstasiak/repaymentassistant/strings").getString("ADD DEBT"));
    }

    /**
     * Creates an edit debt form
     *
     * @param parent The debts list frame that created this form
     * @param controller The controller that handles the main view
     * @param debt The debt instance that is being edited
     */
    public AddEditFrame(DebtsListFrame parent, Controller controller, Debt debt) {
        this.parent = parent;
        this.controller = controller;
        initComponents();
        this.editing = debt;
        refInput.setValue(debt.getDescription());
        balInput.setValue(debt.getOutstandingBalance() / 100);
        rateInput.setValue(debt.getInterestRate() * 100);
        payInput.setValue(debt.getMinimumPayment() / 100);
        errorLabel.setVisible(false);
        this.setTitle(java.util.ResourceBundle.getBundle("com/kacperstasiak/repaymentassistant/strings").getString("EDIT DEBT"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refPanel = new javax.swing.JPanel();
        refLabel = new javax.swing.JLabel();
        refInput = new javax.swing.JFormattedTextField();
        balPanel = new javax.swing.JPanel();
        balLabel = new javax.swing.JLabel();
        balInput = new javax.swing.JFormattedTextField();
        ratePanel = new javax.swing.JPanel();
        rateLabel = new javax.swing.JLabel();
        rateInput = new javax.swing.JFormattedTextField();
        payPanel = new javax.swing.JPanel();
        payLabel = new javax.swing.JLabel();
        payInput = new javax.swing.JFormattedTextField();
        cancelBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        refLabel.setLabelFor(refInput);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/kacperstasiak/repaymentassistant/strings"); // NOI18N
        refLabel.setText(bundle.getString("DEBT NAME/REFERENCE")); // NOI18N

        javax.swing.GroupLayout refPanelLayout = new javax.swing.GroupLayout(refPanel);
        refPanel.setLayout(refPanelLayout);
        refPanelLayout.setHorizontalGroup(
            refPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(refPanelLayout.createSequentialGroup()
                .addComponent(refLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        refPanelLayout.setVerticalGroup(
            refPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(refPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(refLabel)
                .addComponent(refInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        balLabel.setLabelFor(balInput);
        balLabel.setText(bundle.getString("OUTSTANDING BALANCE")); // NOI18N

        javax.swing.GroupLayout balPanelLayout = new javax.swing.GroupLayout(balPanel);
        balPanel.setLayout(balPanelLayout);
        balPanelLayout.setHorizontalGroup(
            balPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balPanelLayout.createSequentialGroup()
                .addComponent(balLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(balInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        balPanelLayout.setVerticalGroup(
            balPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(balLabel)
                .addComponent(balInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rateLabel.setLabelFor(rateInput);
        rateLabel.setText(bundle.getString("ANNUAL INTEREST RATE")); // NOI18N

        javax.swing.GroupLayout ratePanelLayout = new javax.swing.GroupLayout(ratePanel);
        ratePanel.setLayout(ratePanelLayout);
        ratePanelLayout.setHorizontalGroup(
            ratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratePanelLayout.createSequentialGroup()
                .addComponent(rateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ratePanelLayout.setVerticalGroup(
            ratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rateLabel)
                .addComponent(rateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        payLabel.setLabelFor(payInput);
        payLabel.setText(bundle.getString("NEXT MINIMUM PAYMENT")); // NOI18N

        javax.swing.GroupLayout payPanelLayout = new javax.swing.GroupLayout(payPanel);
        payPanel.setLayout(payPanelLayout);
        payPanelLayout.setHorizontalGroup(
            payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payPanelLayout.createSequentialGroup()
                .addComponent(payLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        payPanelLayout.setVerticalGroup(
            payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(payLabel)
                .addComponent(payInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cancelBtn.setText(bundle.getString("CANCEL")); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        okBtn.setText(bundle.getString("OK")); // NOI18N
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(200, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText(bundle.getString("ADDEDIT ERROR")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okBtn))
                    .addComponent(balPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ratePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okBtn)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        errorLabel.setText(java.util.ResourceBundle.getBundle("com/kacperstasiak/repaymentassistant/strings").getString("ADDEDIT ERROR"));
        errorLabel.setVisible(false);
        String ref = ((String) refInput.getValue());
        double bal = ((Number) balInput.getValue()).doubleValue();
        double rate = ((Number) rateInput.getValue()).doubleValue();
        double pay = ((Number) payInput.getValue()).doubleValue();
        int balance = (int) Math.floor(bal * 100);
        int minpay = (int) Math.floor(pay * 100);
        if (ref.length() < 1) {
            errorLabel.setText(java.util.ResourceBundle.getBundle("com/kacperstasiak/repaymentassistant/strings").getString("INVALID REFERENCE"));
            errorLabel.setVisible(true);
            return;
        }
        if (balance < 0) {
            errorLabel.setText(java.util.ResourceBundle.getBundle("com/kacperstasiak/repaymentassistant/strings").getString("INVALID BALANCE"));
            errorLabel.setVisible(true);
            return;
        }
        if (rate < 0.0 || rate >= 100.0) {
            errorLabel.setText(java.util.ResourceBundle.getBundle("com/kacperstasiak/repaymentassistant/strings").getString("INVALID INTEREST RATE"));
            errorLabel.setVisible(true);
            return;
        }
        if (minpay < 0) {
            errorLabel.setText(java.util.ResourceBundle.getBundle("com/kacperstasiak/repaymentassistant/strings").getString("INVALID MIN PAYMENT"));
            errorLabel.setVisible(true);
            return;
        }
        
        
        if (editing != null) {
            controller.editDebt(editing, ref, balance, rate / 100, minpay);
        } else {
            controller.addDebt(ref, balance, rate / 100, minpay);
        }
        controller.updateView();
        parent.closeAddEditMenu();

    }//GEN-LAST:event_okBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        parent.closeAddEditMenu();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        toFront();
        requestFocus();
    }//GEN-LAST:event_formWindowLostFocus

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField balInput;
    private javax.swing.JLabel balLabel;
    private javax.swing.JPanel balPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton okBtn;
    private javax.swing.JFormattedTextField payInput;
    private javax.swing.JLabel payLabel;
    private javax.swing.JPanel payPanel;
    private javax.swing.JFormattedTextField rateInput;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JPanel ratePanel;
    private javax.swing.JFormattedTextField refInput;
    private javax.swing.JLabel refLabel;
    private javax.swing.JPanel refPanel;
    // End of variables declaration//GEN-END:variables
}
